# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'SafeT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON', '~> 4.0' 
 # Pods for SafeT
 
pod 'CSV.swift', '~> 2.2.1'

  target 'SafeTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SafeTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end



